##version: '3.9'

##services:
#  lxpay_db_service:
#    container_name: lxpay_db
#    image: postgres
#    restart: on-failure
##    restart: always
#    env_file:
#      - ./.env
#    ports:
#      - 5432:5432
#    volumes:
#      - lxpay_db_data:/var/lib/postgresql/data

  ##lxpay_web_service:
    ##container_name: lxpay_web
    ##build:
    ##  context: ./
    ##  dockerfile: Dockerfile
      #target: devstage
    ##env_file:
    ##  - ./.env
    #command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
    ##volumes:
    #  - .:/home/useful/app
    ##  - .:/usr/src
    ##  - ./media:/usr/src/media
    #- ./media:/usr/src/app/media
    ##ports:
    ##  - 8000:8000
    #environment:
    #  POSTGRES_USER: postgres
    #  POSTGRES_DB: habr_db
    #  POSTGRES_PASSWORD: hg26alksup98
    ## restart: always
#    depends_on:
#      - lxpay_db_service
#    command: ./start-reload.sh
    #tty: true
#
#centrifugo:
#  container_name: centrifugo
#  image: centrifugo/centrifugo:v4
#  volumes:
#    - ./config.json:/centrifugo/config.json
#  command: centrifugo -c config.json
#  ports:
#    - 8000:8000
#  ulimits:
#    nofile:
#      soft: 65535
#      hard: 65535


#
#volumes:
#  lxpay_db_data:



#networks:
#  default:
#    external:
#      name: useful-net
